name: DiceRoller
author: Inamine
description: This plugin rolls common dice from roleplaying games!
website: https://www.spigotmc.org/resources/dice-roller-roleplay-dice.22408/
main: me.inamine.DiceRoller
version: 1.4.0
commands:
    roll:
        description: Rolls a die.
        usage: /<command> <d4/d6/d8/d10/d12/d20/d100>
    broll:
        description: Rolls a die and broadcasts result.
        usage: /<command> <d4/d6/d8/d10/d12/d20/d100>
    diceroller:
        description: Gives info with perm diceroller.info
    diceroller reload:
        description: Reloads config file
permissions:
    diceroller.roll:
        default: true
    diceroller.roll.bypass:
        default: op
    diceroller.broadcast:
        default: op
    diceroller.broadcast.bypass:
        default: op
    diceroller.broadcast.view:
        default: true
    diceroller.reload:
        default: op
    diceroller.info:
        default: true